Add options to skip starting and stopping Trafodion in test scripts
Add options to pass in a parameter so the script will skip starting
and/or stopping Trafodion. This will make it easier when debugging
issues found by the tests launched by these scripts.  The options
are SKIPSTART, SKIPSTOP, SKIPSTARTSTOP. To use one of these
options it needs to be the first input parameter to the script. A
lso add core file reporting to the JDBC tests.

Change-Id: I3461d99a7500f1c0e0a71fde94108ddb558201fd

diff --git a/modules/traf/templates/buildtest/run-jdbc_test.sh.erb b/modules/traf/templates/buildtest/run-jdbc_test.sh.erb
--- a/modules/traf/templates/buildtest/run-jdbc_test.sh.erb
+++ b/modules/traf/templates/buildtest/run-jdbc_test.sh.erb
@@ -20,6 +20,27 @@
 source "/usr/local/bin/traf-functions.sh"
 log_banner
 
+# check to see if first argument is one of the following :
+# SKIPSTART SKIPSTOP SKIPSTARTSTOP
+SKIPSTART=""
+SKIPSTOP=""
+
+if [ "$1" = "SKIPSTART" ]
+then
+  SKIPSTART=1
+  shift
+elif [ "$1" = "SKIPSTOP" ]
+then
+  SKIPSTOP=1
+  shift
+elif [ "$1" = "SKIPSTARTSTOP" ]
+then
+  SKIPSTART=1
+  SKIPSTOP=1
+  shift
+fi
+
+# assign input parameters
 export TRAF_DIR="$1"                   # location of trafodion/core
 export DCS_INSTALL_DIR="$2"            # location of trafodion/dcs
 export JAVA_HOME="$3"                  # Java SDK Home Directory
@@ -58,8 +79,8 @@ set -x
 
 # start trafodion
 cd $WORKSPACE
-/usr/local/bin/install-traf.sh "$TRAF_DIR" "$DCS_INSTALL_DIR" "6" "installdrivers" || exit 1
-
+ulimit -c unlimited
+if [ -z $SKIPSTART ]; then /usr/local/bin/install-traf.sh "$TRAF_DIR" "$DCS_INSTALL_DIR" "6" "installdrivers" || exit 1; fi
 
 # run jdbc_test
 log_banner "jdbc_test.py"
@@ -70,8 +91,20 @@ cd "$WORKSPACE/$TEST_DIR"
 jdbcRes=$?
 
 cd $WORKSPACE
-/usr/local/bin/uninstall-traf.sh "$TRAF_DIR/sqf"
+if [ -z $SKIPSTOP ]; then /usr/local/bin/uninstall-traf.sh "$TRAF_DIR/sqf"; fi
 
-# exit with jdbc_test.py return code
+# Report on parent directory of $TRAF_DIR
+# Any core files means failure
+source_env test
+report_on_corefiles "${WORKSPACE}"
+coreCount=$?
+if [[ $coreCount -gt 0 ]]; then
+  echo
+  echo "ERROR : Found $coreCount core files"
+  echo
+fi
+
+jdbcRes=$(( jdbcRes + coreCount ))
+
+# exit with sum of return code from jdbc_test.py and report_on_corefiles
 exit $jdbcRes
-
diff --git a/modules/traf/templates/buildtest/run-pyodbc_test.sh.erb b/modules/traf/templates/buildtest/run-pyodbc_test.sh.erb
--- a/modules/traf/templates/buildtest/run-pyodbc_test.sh.erb
+++ b/modules/traf/templates/buildtest/run-pyodbc_test.sh.erb
@@ -21,6 +21,27 @@ source "/usr/local/bin/traf-functions.sh"
 log_banner
 source "$HOME/.bashrc"
 
+# check to see if first argument is one of the following :
+# SKIPSTART SKIPSTOP SKIPSTARTSTOP
+SKIPSTART=""
+SKIPSTOP=""
+
+if [ "$1" = "SKIPSTART" ]
+then
+  SKIPSTART=1
+  shift
+elif [ "$1" = "SKIPSTOP" ]
+then
+  SKIPSTOP=1
+  shift
+elif [ "$1" = "SKIPSTARTSTOP" ]
+then
+  SKIPSTART=1
+  SKIPSTOP=1
+  shift
+fi
+
+# assign input parameters
 export TRAF_DIR="$1"                   # location of trafodion/core
 export DCS_INSTALL_DIR="$2"            # location of trafodion/dcs
 export TEST_DIR="$3"                   # location of pyodbc tests
@@ -53,8 +74,8 @@ else
   set -x
   # start trafodion
   cd $WORKSPACE
-  /usr/local/bin/install-traf.sh "$TRAF_DIR" "$DCS_INSTALL_DIR" "$NUM_DCS" "installdrivers" || exit 1
-
+  ulimit -c unlimited
+  if [ -z $SKIPSTART ]; then /usr/local/bin/install-traf.sh "$TRAF_DIR" "$DCS_INSTALL_DIR" "$NUM_DCS" "installdrivers" || exit 1; fi
 
   # run pyodbc tests
   log_banner "config.sh"
@@ -87,7 +108,7 @@ else
   fi
 
   cd $WORKSPACE
-  /usr/local/bin/uninstall-traf.sh "$TRAF_DIR/sqf"
+  if [ -z $SKIPSTOP ]; then /usr/local/bin/uninstall-traf.sh "$TRAF_DIR/sqf"; fi
 
   # Report on parent directory of $TRAF_DIR
   # Any core files means failure
@@ -99,6 +120,8 @@ else
     echo "ERROR : Found $coreCount core files"
     echo
   fi
+
+  toxRes=$(( toxRes + coreCount ))
 fi
 
 set -x
@@ -113,6 +136,6 @@ then
   cp -rp .testrepository logs
 fi
 
-# exit with tox return code
+# exit with sum of return codes from tox and report_on_corefiles
 exit $toxRes
 
