Fix problem with Phoenix T2 tests not getting hadoop distro
Fix problem with the Phoenix T2 tests not getting the right
hadoop distro information. This causes it to fail on
Hortonworks machines.

Change-Id: I9e6c4ab111bb14fbf8a0c38444984084190cc84c
Closes-Bug: 1394801

diff --git a/modules/traf/templates/buildtest/run-phoenix_test.sh.erb b/modules/traf/templates/buildtest/run-phoenix_test.sh.erb
--- a/modules/traf/templates/buildtest/run-phoenix_test.sh.erb
+++ b/modules/traf/templates/buildtest/run-phoenix_test.sh.erb
@@ -25,24 +25,36 @@ export DCS_INSTALL_DIR="$2"            # location of trafodion/dcs
 export JAVA_HOME="$3"                  # Java SDK Home Directory
 export TEST_DIR="$4"                   # location of trafodion/phoenix_test
 export TEST_JDBC_TYPE="$5"             # JDBC type T4 or T2
+export TEST_HADOOP_DISTRO="$6"         # Hadoop Distro being tested 
+                                       # (CDH51 or CM51 for Cloudera 5.1.x OR
+                                       # HDP21 for Hortonworks 2.1.x)
 export PATH=$JAVA_HOME/bin:$PATH       # add $JAVA_HOME/bin to the path
 
 # check number of parameters
 # if more than 4 parameters then we are also passing in tests to run
 # NOTE: tests should be delimited by a comma with no space.  i.e. AlterTableTest,ArithmeticQueryTest
-if [ $# -gt 5 ]; then
-  shift
-  shift
-  shift
-  shift
-  shift
+if [ $# -gt 6 ]; then
+  shift 6
   TESTS="$*"
-elif [ $# -lt 5 ]; then
+elif [ $# -lt 6 ]; then
   echo "ERROR: Incorrect number of input parameters."
   exit 1
 fi
 
 set -x
+
+# check TEST_HADOOP_DISTRO input to make sure it's valid
+
+# remove all dots and change to upper case
+TEST_HADOOP_DISTRO=$(echo ${TEST_HADOOP_DISTRO//\./} | tr '[a-z]' '[A-Z]')
+if [[ $TEST_HADOOP_DISTRO == CDH51* ]] || [[ $TEST_HADOOP_DISTRO == CM51* ]]; then
+    TEST_HADOOP_DISTRO="CDH51"
+elif [[ $TEST_HADOOP_DISTRO == HDP21* ]]; then
+    TEST_HADOOP_DISTRO="HDP21"
+else
+    echo "ERROR: Unknown Hadoop Distro $TEST_HADOOP_DISTRO."
+    exit 1
+fi
 
 # check TEST_JDBC_TYPE and set TEST_JDBC_FILE based on it
 TEST_JDBC_TYPE=$(echo $TEST_JDBC_TYPE | tr "[:lower:]" "[:upper:]")
@@ -75,7 +87,7 @@ cd "$WORKSPACE/$TEST_DIR"
 if [ -z "$TESTS" ]; then
   ./phoenix_test.py --target=localhost:37800 --user=<%= jenkins_test_user %> --pw=<%= jenkins_test_password %> \
        --targettype=TR --javahome=$JAVA_HOME \
-       --jdbccp=$TEST_JDBC_FILE --jdbctype=$TEST_JDBC_TYPE
+       --jdbccp=$TEST_JDBC_FILE --jdbctype=$TEST_JDBC_TYPE --hadoop=$TEST_HADOOP_DISTRO
   phoenixRes=$?
 elif [ "$TESTS" = "DONT_RUN_TESTS" ]; then
   echo "INFO: Will NOT run any phoenix tests as requested. You should not see this message in the normal Jenkins job phoenix_test! This should only be used to turn off testing of the experimetal jobs."
@@ -83,7 +95,7 @@ elif [ "$TESTS" = "DONT_RUN_TESTS" ]; then
 else
   ./phoenix_test.py --target=localhost:37800 --user=<%= jenkins_test_user %> --pw=<%= jenkins_test_password %> \
        --targettype=TR --javahome=$JAVA_HOME \
-       --jdbccp=$TEST_JDBC_FILE --jdbctype=$TEST_JDBC_TYPE --tests=$TESTS
+       --jdbccp=$TEST_JDBC_FILE --jdbctype=$TEST_JDBC_TYPE --hadoop=$TEST_HADOOP_DISTRO --tests=$TESTS
   phoenixRes=$?
 fi
 
