Fix problem with publishing .tar.gz files to the CDN
Changed the algorithm so that files are individually uploaded.
This way they can be processed correctly. Apparently, Swift
also has a bug where you specifying the header content-type is
ignored during upload. To get around that problem we run a POST
command after uploading to make sure the headers we want are set.
Also changed /usr/local/binuseObjectStorage.sh to not be world
readable/writeable since we have user information in that file.
Due to that change jenkins needs to be given sudo access to that file.

Change-Id: If6ae68f306f28acb7c0d20f2201bfb8727dc26f2

diff --git a/modules/traf/templates/useObjectStorage.sh.erb b/modules/traf/templates/useObjectStorage.sh.erb
--- a/modules/traf/templates/useObjectStorage.sh.erb
+++ b/modules/traf/templates/useObjectStorage.sh.erb
@@ -23,19 +23,19 @@
 export PRGNAME=$(basename $0)
 scriptDir=$(dirname $0)
 if [[ $scriptDir == "." ]]; then scriptDir=`pwd`; fi
-backupContainer="BackupContainer"
-cdnContainer="trafcdn"
-fName=""
-outputFile=""
-container=""
+export backupContainer="BackupContainer"
+export cdnContainer="trafcdn"
+export container=""
 containerSub=""
+tfName=""
+outputFile=""
 swiftVerb=""
 swiftFile=""
 swiftCmdArgs=""
 res=0
 
 # set up environment to use swift
-swift=/usr/local/bin/swift
+export swift=/usr/local/bin/swift
 export OS_REGION_NAME=region-a.geo-1
 export OS_DNS_SERVICE_TYPE=hpext:dns
 export OS_AUTH_URL=https://region-a.geo-1.identity.hpcloudsvc.com:35357/v2.0/
@@ -82,6 +82,94 @@ ProgramHelp() {
   "
 }
 
+#-----------------------------------------
+# Desc  : Upload a file to object storage
+# Usage : SwiftUpload <file_name>
+#-----------------------------------------
+
+SwiftUpload() {
+    fName=$1
+    uploadOptions="--retries=3 --changed --skip-identical"
+    headerOptions=""
+    host=$(hostname -s)
+
+    # check if file size is greater than 4.99 GB (5,358,000,000 bytes)
+    # if file size is too big then segment the file to 2 GB chunks
+    fSize=$(stat -c%s "$fName")
+    if [[ $fSize -gt 5358000000 ]]; then
+        uploadOptions+=" -S 2147483648"
+    fi
+
+    # set options based on container
+    if [[ $container = "$backupContainer" ]]; then
+        # check to see if fName contains absolute path
+        if [[ -n ${fName%%/*} ]]; then
+            echo "ERROR: Must use absolute path when uploading to the container $backupContainer"
+            exit 1
+        else
+            # get current md5sum of file
+            fMd5sum=$(md5sum $fName | awk '{print $1}')
+
+            # get md5sum of file from the cloud
+            fCloudMd5sum=$($swift stat $container ${host}${fName} 2>/dev/null | grep "ETag:" | awk '{print $2}')
+
+            if [[ "$fMd5sum" = "$fCloudMd5sum" ]]; then
+                echo "INFO: File $fName has not changed since the last upload. Skipping upload ..."
+                rc=$?
+            else
+                # if fCloudMd5sum is not empty then file has been uploaded before
+                if [[ -n $fCloudMd5sum ]]; then
+                    # set header X-Delete-After to 30 days so we do not keep
+                    # more than 30 days worth of previous version of the file
+                    echo "INFO: Setting $fName to expire in 30 days ..."
+                    $swift post -H 'x-delete-after: 259200' $container ${host}${fName}
+                    rc=$?
+                fi
+
+                echo "INFO: Uploading file $fName to container $container ..."
+                $swift upload $uploadOptions $headerOptions $container/$host $fName
+                (( rc += $? ))
+            fi
+        fi
+    elif [[ $container = "$cdnContainer" ]]; then
+        # check to see if fName starts with daily, old-release, opencart, pre-release, release, or sandbox
+        if [[ $fName =~ ^daily/.*|^old-release/.*|^opencart/.*|^pre-release/.*|^release/.*|^sandbox/.* ]]; then
+            # Swift sets content-type for *.tar.gz files to application/x-tar
+            # This is the correct content-type. However different browsers handle 
+            # this file type differently which causes the file name to get mangled 
+            # by the browser.  We will set the content-type to application/octet-stream
+            # to force the browsers to always download these files with the correct extension
+            if [[ $fName =~ .*.tar.gz ]]; then
+                headerOptions+=" -H content-type:application/octet-stream"
+            fi
+
+            # if daily or pre-release build
+            # set header X-Delete-After to 30 days so we do not keep
+            # more than 30 days worth of daily builds
+            if [[ $fName =~ ^daily/.*|^pre-release/.* ]]; then
+                echo "INFO: Setting $fName to expire in 30 days ..."
+                headerOptions+=" -H x-delete-after:259200"
+            fi
+
+            echo "INFO: Uploading $fName to container $container ..."
+            $swift upload $uploadOptions $headerOptions $container $fName
+            rc=$?
+
+            # There appears to be a bug in the swift client. The header
+            # content-type is ignored when passed via upload.
+            # run a POST command to make sure it is set
+            echo "INFO: Setting file content-type again to be sure it is set ..."
+            $swift post $headerOptions $container $fName
+            (( rc += $? ))
+        else
+            echo "ERROR: Path must start with one of the following (daily/, old-release/, opencart/, pre-release/, release/, or sandbox/)"
+            echo "       when uploading to the container $cdnContainer"
+            exit 1
+        fi
+    fi
+    return $rc
+}
+
 
 #======================
 # Main Program
@@ -107,7 +195,7 @@ else
                 ;;
             u)  # Upload file
                 swiftVerb="upload"
-                fName="$OPTARG"
+                tfName="$OPTARG"
                 ;;
             d)  # Download file
                 swiftVerb="download"
@@ -152,77 +240,24 @@ elif [[ $swiftVerb = "download" ]]; then
     fi
     res=$?
 elif [[ $swiftVerb = "upload" ]]; then
-    uploadOptions="--retries=3 --changed --skip-identical"
-    host=$(hostname -s)
-
-    # Swift sets content-type for *.tar.gz files to application/x-tar
-    # This is the correct content-type. However different browsers handle 
-    # this file type differently which causes the file name to get mangled 
-    # by the browser.  We will set the content-type to application/octet-stream
-    # to force the browsers to always download these files with the correct extension
-    if [[ $fName =~ .*.tar.gz ]]; then
-      uploadOptions+=" -H content-type:application/octet-stream"
-    fi
-
-    if [[ -f $fName ]]; then
-        # check if file size is greater than 4.99 GB (5,358,000,000 bytes)
-        # if file size is too big then segment the file to 2 GB chunks
-        fSize=$(stat -c%s "$fName")
-        if [[ $fSize -gt 5358000000 ]]; then
-            uploadOptions+=" -S 2147483648"
-        fi
-
-        # get current md5sum of file
-        fMd5sum=$(md5sum $fName | awk '{print $1}')
-    fi
-
-    # set options based on container
-    if [[ $container = "$backupContainer" ]]; then
-        # check to see if fName contains absolute path
-        if [[ -n ${fName%%/*} ]]; then
-            echo "ERROR: Must use absolute path when uploading to the container $backupContainer"
-            exit 1
-        else
-            # get md5sum of file from the cloud
-            fCloudMd5sum=$($swift stat $container ${host}${fName} 2>/dev/null | grep "ETag:" | awk '{print $2}')
-
-            if [[ "$fMd5sum" = "$fCloudMd5sum" ]]; then
-                echo "INFO: File $fName has not changed since the last upload. Skipping upload ..."
-                res=$?
-            else
-                # if fCloudMd5sum is not empty then file has been uploaded before
-                if [[ -n $fCloudMd5sum ]]; then
-                    # set header X-Delete-After to 30 days so we do not keep
-                    # more than 30 days worth of previous version of the file
-                    echo "INFO: Setting $fName to expire in 30 days ..."
-                    $swift post -H 'x-delete-after: 259200' $container ${host}${fName}
-                    res=$?
-                fi
-
-                echo "INFO: Uploading file $fName to container $container ..."
-                $swift upload $uploadOptions $container/$host $fName
-                (( res += $? ))
-            fi
-        fi
-    elif [[ $container = "$cdnContainer" ]]; then
+    # Normally swift does not care whether you are uploading a file
+    # or a directory. However, since we need special processing
+    # for *.tar.gz files we need to process each file in a directory
+    #
+    # Check if $tfName is a directory and process accordingly
+    if [[ ! -d $tfName ]]; then
+        echo "INFO: $tfName is a file ..."
+        SwiftUpload $tfName
+        res=$?
+    else
+        echo "INFO: $tfName is a directory ..."
         # since fName can be a directory check to make sure that fName actually contains files to be uploaded
         if [[ $(find $fName -type f | wc -l) -ne 0 ]]; then
-            # check to see if fName starts with daily, old-release, opencart, pre-release, release, or sandbox
-            if [[ $fName =~ ^daily/.*|^old-release/.*|^opencart/.*|^pre-release/.*|^release/.*|^sandbox/.* ]]; then
-                if [[ $fName =~ ^daily/.*|^pre-release/.* ]]; then
-                    # set header X-Delete-After to 30 days so we do not keep
-                    # more than 30 days worth of daily builds
-                    echo "INFO: Setting $fName to expire in 30 days ..."
-                    uploadOptions+=" -H x-delete-after:259200"
-                fi
-                echo "INFO: Uploading $fName to container $container ..."
-                $swift upload $uploadOptions $container $fName
+            find $tfName -type f | while read tFile
+            do
+                SwiftUpload $tFile
                 res=$?
-            else
-                echo "ERROR: Path must start with one of the following (daily/, old-release/, opencart/, pre-release/, release/, or sandbox/)"
-                echo "       when uploading to the container $cdnContainer"
-                exit 1
-            fi
+            done
         else
             echo "WARNING: There were no files found in $fName. Upload to container $cdnContainer cancelled."
         fi
